// Shared by the gallery and native catalog smoke test.
export const kitExamples: Record<string, Record<string, unknown>> = {
  "kit-button": { label: "Button" },
  "kit-checkbox": { label: "Checkbox" },
  "kit-switch": { label: "Switch" },
  "kit-radio": { label: "Radio" },
  "kit-toggle": { label: "Toggle" },
  "kit-badge": { count: 5 },
  "kit-tag": { label: "Tag" },
  "kit-spinner": {},
  "kit-skeleton": {},
  "kit-separator": { label: "Separator" },
  "kit-progress": { value: 45 },
  "kit-progress-circle": { value: 45 },
  "kit-rating": { value: 3 },
  "kit-pagination": { page: 2, totalPages: 10 },
  "kit-link": { label: "Link", href: "https://example.com" },
  "kit-avatar": { name: "Kit Test" },
  "kit-group-box": { title: "Group" },
  "kit-collapsible": { open: true },
  "kit-slider": { value: [20, 80] },
  "kit-calendar": { value: "2026-09-13" },
  "kit-date-picker": { value: "2026-09-13" },
  "kit-color-picker": { value: "#3366ff" },
  "kit-tabs": { items: ["One", "Two"] },
  "kit-radio-group": { items: ["One", "Two"] },
  "kit-accordion": { items: [{ title: "Details", content: "Body" }], openIndices: [0] },
  "kit-description-list": { items: [{ label: "Name", value: "Kit" }] },
  "kit-breadcrumb": { items: ["Home", "Kit"] },
  "kit-alert": { title: "Title", message: "Message" },
  "kit-empty": { title: "Empty" },
  "kit-icon": { name: "check" },
  "kit-kbd": { keystroke: "cmd-k" },
  "kit-data-table": { columns: [{ key: "name" }], rows: [{ name: "Kit" }] },
  "kit-popover": { label: "Open", open: true },
  "kit-dialog": { title: "Dialog", open: true },
  "kit-sheet": { title: "Sheet", open: true },
  "kit-select": { items: ["One", "Two"], value: "One" },
  "kit-combobox": { items: ["One", "Two"], value: ["Two"], multiple: true },
  "kit-form": { items: [{ label: "Field", required: true }] },
  "kit-field": { label: "Field" },
  "kit-stepper": { items: ["First", "Second"] },
  "kit-sidebar": { items: ["First", "Second"] },
  "kit-sidebar-header": {},
  "kit-sidebar-footer": {},
  "kit-sidebar-toggle": {},
  "kit-status-bar": {},
  "kit-clipboard": { value: "Copied value" },
  "kit-message": {},
  "kit-message-group": {},
  "kit-message-header": {},
  "kit-message-content": {},
  "kit-message-footer": {},
  "kit-bubble": {},
  "kit-bubble-group": {},
  "kit-marker": {},
  "kit-attachment-group": {},
  "kit-input": { value: "Editable" },
  "kit-textarea": { value: "Multiline\ntext" },
  "kit-editor": { value: "const x = 1", language: "javascript" },
  "kit-number-input": { value: "12" },
  "kit-otp-input": { value: "123456" },
  "kit-tree": {
    items: [
      { id: "root", label: "Root", expanded: true, children: [{ id: "leaf", label: "Leaf" }] },
    ],
  },
  "kit-carousel": { pagination: true },
  "kit-dropdown-menu": { label: "Menu", items: ["First", "Second"] },
  "kit-context-menu": { items: ["First", "Second"] },
  "kit-theme": { mode: "light" },

  "kit-line-chart": {
    data: [
      { label: "January", value: 10 },
      { label: "February", value: 25 },
    ],
  },
  "kit-area-chart": {
    data: [
      { label: "January", value: 10 },
      { label: "February", value: 25 },
    ],
  },
  "kit-bar-chart": {
    data: [
      { label: "January", value: 10 },
      { label: "February", value: 25 },
    ],
  },
  "kit-pie-chart": {
    data: [
      { label: "January", value: 10 },
      { label: "February", value: 25, color: "#77cc99" },
    ],
  },
  "kit-candlestick-chart": {
    data: [
      { label: "Mon", open: 10, high: 15, low: 8, close: 12 },
      { label: "Tue", open: 12, high: 16, low: 9, close: 10 },
    ],
  },
  "kit-radar-chart": {
    data: [
      { label: "Speed", value: 10 },
      { label: "Quality", value: 25 },
      { label: "Reach", value: 20 },
    ],
  },
  "kit-sankey-chart": {
    data: [{ label: "Source" }, { label: "Target" }],
    links: [{ source: 0, target: 1, value: 5 }],
  },
  "kit-dock": { panels: [{ id: "editor", title: "Editor" }] },
  "kit-resizable": { sizes: [200, 200] },
  "kit-command": { items: ["Open project", "Save project", "Close window"] },
  "kit-list": { items: ["First", "Second", "Third"], searchable: true },
  "kit-label": { label: "Native label" },
  "kit-shimmer-text": { label: "Working on it…" },
  "kit-tooltip": { label: "Helpful information" },
  "kit-hover-card": { label: "Hover for details" },
  "kit-notification": {
    open: true,
    title: "Saved",
    message: "Your changes are ready",
    autohide: false,
  },
  "kit-attachment": {
    title: "Project notes",
    description: "Markdown document",
    status: "complete",
  },
  "kit-settings": {
    pages: [
      {
        title: "General",
        groups: [
          {
            title: "Preferences",
            items: [{ title: "Display name", description: "Your public name" }],
          },
        ],
      },
    ],
  },
  "kit-message-scroller": {},
  "kit-title-bar": {},
  "kit-window-border": {},
}
