/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuiRenderer {
  constructor(eventCallback?: (error: Error | null, event: EventPayload | null) => void)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns array of destroyed IDs
   * so JS can clean up event handlers for the entire subtree.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /**
   * Set a custom prop on an element (for non-div/text elements like input, editor, diff).
   * Key is the prop name, value is JSON-encoded.
   */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. Returns JSON string or null. */
  getCustomProp(id: number, key: string): string | null
  /** Signal that a batch of mutations is complete. Triggers re-render. */
  commitMutations(): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   * ```text
   * ["createElement",    id, "type"]
   * ["destroyElement",   id]
   * ["appendChild",      parentId, childId]
   * ["removeChild",      parentId, childId]
   * ["insertBefore",     parentId, childId, beforeId]
   * ["setStyle",         id, { ...style } | "{styleJson}"]
   * ["setText",          id, "content"]
   * ["setEventListener", id, "eventType", true|false]
   * ["setRoot",          id]
   * ["setCustomProp",      id, "key", value | "{valueJson}"]
   * ["setCustomPropValue", id, "key", value]
   * ```
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /** Whether JavaScript must drive the native event loop with `tick()`. */
  requiresTick(): boolean
  /**
   * First-party renderers emit window lifecycle events through the normal
   * callback, allowing JS to avoid timer-based liveness and size polling.
   */
  supportsWindowEvents(): boolean
  /**
   * The paintable size of the window in logical pixels, excluding any
   * platform title bar. This used to answer a hardcoded 800x600, so anything
   * that turned a mouse position into layout coordinates pointed at the
   * wrong place on every window that was not exactly that size.
   */
  getWindowSize(): WindowSize
  getWindowInsets(): WindowInsets
  /**
   * Stop the native event loop and release the window. This explicit
   * lifecycle hook lets Vue unmount or hot-remount without keeping Node's
   * process alive.
   */
  close(): void
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Bring the window forward and focus it. This also reveals a window opened
   * with `show: false`.
   */
  activateWindow(): void
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by index, optionally preserving a pixel offset
   * inside that item. Negative offsets are valid for prepend restoration.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * Return `[itemIndex, offsetInItemPx, viewportHeightPx]` for a virtual
   * list, or null for an ordinary element.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * Deltas are pixels: negative `delta_y` scrolls down, negative `delta_x`
   * pans right, matching `TestGpuiRenderer::simulate_scroll_wheel`.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  timelineGetState(): TimelineState
  timelinePlay(): TimelineState
  timelinePause(): TimelineState
  timelineSeek(currentTimeMs: number): TimelineState
  timelineSetPlaybackRate(playbackRate: number): TimelineState
  /** Configure the bounded decoded-audio queue. Frames are interleaved f32 PCM. */
  configureAudio(sampleRate: number, channels: number, capacityFrames?: number | undefined | null): AudioBufferState
  /** Enqueue one decoded chunk without JSON serialization or per-sample FFI calls. */
  enqueueAudioFrames(samples: Float32Array): AudioBufferState
  /** Consume up to `maxFrames` from a native audio backend or custom host. */
  dequeueAudioFrames(maxFrames: number): Float32Array
  clearAudioFrames(): AudioBufferState
  getAudioBufferState(): AudioBufferState
  captureScreenshot(path: string): void
}

export interface AudioBufferState {
  sampleRate: number
  channels: number
  capacityFrames: number
  queuedFrames: number
  droppedFrames: number
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in `EVENT_PROPS` on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /** Native viewport width. Populated for `windowResize`. */
  width?: number
  /** Native viewport height. Populated for `windowResize`. */
  height?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or `ClickEvent::is_right_click()`.
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  modifiers?: EventModifiers
}

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

export interface TimelineState {
  currentTimeMs: number
  playbackRate: number
  playing: boolean
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  /** Retain and query the native tree without opening a platform window. */
  headless?: boolean
  title?: string
  /**
   * The name used inside the macOS "Hide" and "Quit" menu items. Defaults to
   * `title`. It does NOT set the title of the application menu itself: macOS
   * takes that from the executable, and only a `.app` bundle changes it.
   */
  appName?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /** Give the window focus when it opens. Ignored by GPUI on Linux. */
  focus?: boolean
  /**
   * Show the window when it opens. Call `activateWindow()` to reveal it.
   * Ignored by GPUI on Linux.
   */
  show?: boolean
}

export interface WindowSize {
  width: number
  height: number
}
